from __future__ import annotations

import argparse
import asyncio
import sys

import qrcode

from .client import HermesMobileConnector


def prompt_if_missing(value: str | None, *, label: str, optional: bool = False) -> str | None:
    if value is not None:
        return value
    response = input(f"{label}: ").strip()
    if response:
        return response
    if optional:
        return None
    raise SystemExit(f"{label} is required.")


def print_qr_code(value: str) -> None:
    qr = qrcode.QRCode(border=1)
    qr.add_data(value)
    qr.make(fit=True)
    qr.print_ascii(tty=sys.stdout.isatty())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="hermes-mobile-connector")
    subparsers = parser.add_subparsers(dest="command", required=True)

    setup = subparsers.add_parser("setup", help="Create a Hermes Mobile account and enroll this host.")
    setup.add_argument("--owner-display-name", help="Display name for the relay account owner.")
    setup.add_argument("--host-display-name", help="Optional label for this Hermes host.")
    setup.add_argument("--relay-url", help="Relay API base URL. Defaults to the hosted production relay.")

    enroll = subparsers.add_parser("enroll", help="Redeem a Hermes Mobile host setup code.")
    enroll.add_argument("--code", required=True, help="Opaque HC1 setup code generated by the Hermes Mobile relay.")
    enroll.add_argument("--display-name", help="Optional label for this Hermes host.")

    subparsers.add_parser("pair-phone", help="Generate a short-lived phone pairing code and QR.")
    subparsers.add_parser("run", help="Run the long-lived Hermes Mobile connector.")
    subparsers.add_parser("status", help="Show the current connector enrollment and runtime state.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    connector = HermesMobileConnector()

    if args.command == "setup":
        try:
            existing_state = connector.state_store.load()
            print(f"Connector is already set up for {existing_state.relay_url}.")
            print("Use `hermes-mobile-connector status` to inspect it, or remove the local state directory to start over.")
            return 1
        except RuntimeError:
            pass

        owner_display_name = prompt_if_missing(args.owner_display_name, label="Owner display name")
        host_display_name = prompt_if_missing(args.host_display_name, label="Host label (optional)", optional=True)
        state = connector.setup(
            owner_display_name=owner_display_name,
            host_display_name=host_display_name,
            relay_url=args.relay_url,
        )
        print(f"Host {state.host_id} is ready for phone pairing against {state.relay_url}")
        print("Next steps:")
        print("1. Start the connector with `hermes-mobile-connector run`.")
        print("2. Generate a phone pairing code with `hermes-mobile-connector pair-phone`.")
        return 0

    if args.command == "enroll":
        state = connector.enroll(code=args.code, display_name=args.display_name)
        print(f"Enrolled host {state.host_id} against {state.relay_url}")
        return 0

    if args.command == "pair-phone":
        pairing = connector.create_phone_pairing_code()
        print("Phone pairing code:")
        print(pairing.display_code)
        if pairing.expires_at:
            print(f"Expires at: {pairing.expires_at}")
        print()
        print("QR code:")
        print_qr_code(pairing.display_code)
        print()
        print("On your phone, open Hermes Mobile and scan this code or enter it manually.")
        return 0

    if args.command == "run":
        asyncio.run(connector.run_forever())
        return 0

    if args.command == "status":
        for line in connector.status_lines():
            print(line)
        return 0

    raise SystemExit(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
