from __future__ import annotations

import argparse
import asyncio

from .client import HermesMobileConnector


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="hermes-mobile-connector")
    subparsers = parser.add_subparsers(dest="command", required=True)

    enroll = subparsers.add_parser("enroll", help="Redeem a Hermes Mobile host setup code.")
    enroll.add_argument("--code", required=True, help="Opaque HC1 setup code generated by the Hermes Mobile relay.")
    enroll.add_argument("--display-name", help="Optional label for this Hermes host.")

    subparsers.add_parser("run", help="Run the long-lived Hermes Mobile connector.")
    subparsers.add_parser("status", help="Show the current connector enrollment and runtime state.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    connector = HermesMobileConnector()

    if args.command == "enroll":
        state = connector.enroll(code=args.code, display_name=args.display_name)
        print(f"Enrolled host {state.host_id} against {state.relay_url}")
        return 0

    if args.command == "run":
        asyncio.run(connector.run_forever())
        return 0

    if args.command == "status":
        for line in connector.status_lines():
            print(line)
        return 0

    raise SystemExit(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
